/**
 * Calculator - CO2 Emission Calculation Engine
 * 
 * Provides methods for calculating CO2 emissions based on distance and transport mode,
 * comparing emissions across transport modes, calculating savings, and estimating
 * carbon credit values.
 */

const Calculator = {
  /**
   * Calculate CO2 emissions for a single trip
   * 
   * Formula: Distance (km) × Emission Factor (kg CO2/km) = Total Emissions (kg)
   * 
   * @param {number} distanceKm - Distance traveled in kilometers
   * @param {string} transportMode - Transport mode key (bicycle, car, bus, truck)
   * @returns {number} CO2 emissions in kg, rounded to 2 decimal places
   */
  calculateEmission: function(distanceKm, transportMode) {
    // Validate inputs
    if (distanceKm < 0 || !CONFIG.EMISSION_FACTORS[transportMode]) {
      console.error(`Invalid inputs: distance=${distanceKm}, mode=${transportMode}`);
      return 0;
    }

    // Get emission factor for the transport mode
    const emissionFactor = CONFIG.EMISSION_FACTORS[transportMode];

    // Calculate total emission
    const emission = distanceKm * emissionFactor;

    // Return rounded to 2 decimal places
    return Math.round(emission * 100) / 100;
  },

  /**
   * Calculate emissions for all transport modes and compare them
   * 
   * Uses car as the baseline (100%) for comparison purposes
   * Results are sorted from lowest to highest emissions
   * 
   * @param {number} distanceKm - Distance traveled in kilometers
   * @returns {Array<Object>} Array of emission results with structure:
   *   [{ mode, label, icon, emission, percentageVsCar }, ...]
   */
  calculateAllModes: function(distanceKm) {
    const results = [];

    // Calculate car emission as baseline for comparison
    const carEmission = this.calculateEmission(distanceKm, 'car');

    // Calculate emissions for each transport mode
    Object.keys(CONFIG.EMISSION_FACTORS).forEach(mode => {
      const emission = this.calculateEmission(distanceKm, mode);
      
      // Calculate percentage vs car baseline
      // If car emission is 0 (edge case), use 100%
      const percentageVsCar = carEmission > 0 
        ? Math.round((emission / carEmission) * 100 * 100) / 100 
        : 100;

      // Add result with mode metadata
      results.push({
        mode: mode,
        label: CONFIG.TRANSPORT_MODES[mode].label,
        icon: CONFIG.TRANSPORT_MODES[mode].icon,
        color: CONFIG.TRANSPORT_MODES[mode].color,
        emission: emission,
        percentageVsCar: percentageVsCar
      });
    });

    // Sort by emission (lowest first) for display
    results.sort((a, b) => a.emission - b.emission);

    return results;
  },

  /**
   * Calculate CO2 savings between two emission values
   * 
   * Used to compare emissions of different transport modes
   * Shows how much CO2 is saved by choosing an alternative mode
   * 
   * @param {number} emission - CO2 emissions of chosen mode (kg)
   * @param {number} baselineEmission - CO2 emissions of baseline mode (kg)
   * @returns {Object} Savings information:
   *   { savedKg: number, percentage: number }
   */
  calculateSavings: function(emission, baselineEmission) {
    // Calculate kg saved
    const savedKg = Math.max(0, baselineEmission - emission);

    // Calculate percentage saved relative to baseline
    // Handle division by zero
    const percentage = baselineEmission > 0 
      ? Math.round((savedKg / baselineEmission) * 100 * 100) / 100 
      : 0;

    return {
      savedKg: Math.round(savedKg * 100) / 100,
      percentage: percentage
    };
  },

  /**
   * Calculate carbon credits generated by this emission amount
   * 
   * 1 carbon credit = CONFIG.CARBON_CREDIT.KG_PER_CREDIT kg CO2
   * Can be used for carbon offset calculations
   * 
   * @param {number} emissionKg - CO2 emissions in kilograms
   * @returns {number} Number of carbon credits, rounded to 4 decimal places
   */
  calculateCarbonCredits: function(emissionKg) {
    // Divide total emissions by kg per credit
    const credits = emissionKg / CONFIG.CARBON_CREDIT.KG_PER_CREDIT;

    // Return rounded to 4 decimal places
    return Math.round(credits * 10000) / 10000;
  },

  /**
   * Estimate carbon credit market price based on credit amount
   * 
   * Uses CONFIG.CARBON_CREDIT price range (min/max BRL)
   * Provides minimum, maximum, and average estimates
   * 
   * @param {number} credits - Number of carbon credits
   * @returns {Object} Price range estimation:
   *   { min: number, max: number, average: number } (all in BRL)
   */
  estimateCreditPrice: function(credits) {
    // Get price range from config
    const priceMin = CONFIG.CARBON_CREDIT.PRICE_MIN_BRL;
    const priceMax = CONFIG.CARBON_CREDIT.PRICE_MAX_BRL;

    // Calculate price estimates
    const minPrice = credits * priceMin;
    const maxPrice = credits * priceMax;
    const averagePrice = (minPrice + maxPrice) / 2;

    return {
      min: Math.round(minPrice * 100) / 100,
      max: Math.round(maxPrice * 100) / 100,
      average: Math.round(averagePrice * 100) / 100
    };
  }
};
